export const PROJECTS = [
  {
    num: "01",
    title: "AI Food Supply Chain Intelligence (Agriflow)",
    category: "Python & Machine Learning",
    desc: "Intelligent food supply chain optimization platform utilizing machine learning to forecast demand, reduce agricultural waste, and streamline logistics. Top 100 JuaraVibeCoding from Google.",
    tech: ["Python", "Machine Learning", "Data Analysis", "Predictive Modeling", "Google Cloud"],
    awards: ["Top 100 JuaraVibeCoding Google (2026)"],
    image: "/images/ResQR/login.png",
    link: "https://github.com/dayricraft",
    linkText: "View Project",
  },
  {
    num: "02",
    title: "AI Material Verification Intelligence (MatVerify)",
    category: "Computer Vision & Deep Learning",
    desc: "Deep learning and computer vision solution for automated material verification and structural assessment, engineered during the Microsoft Hackathon.",
    tech: ["Python", "TensorFlow", "Computer Vision", "Neural Networks", "Deep Learning"],
    awards: ["Microsoft Hackathon (2026)"],
    image: "/images/Capstone/login.png",
    link: "https://github.com/dayricraft",
    linkText: "View Project",
  },
  {
    num: "03",
    title: "Customer Segmentation for Online Retail",
    category: "Data Science & Machine Learning",
    desc: "End-to-end customer segmentation pipeline using RFM analysis and unsupervised clustering on retail transaction datasets. Capstone project from Dicoding Indonesia.",
    tech: ["Python", "Scikit-Learn", "Pandas", "EDA", "RFM Analysis", "Statistical Modeling"],
    awards: ["Capstone Project from Dicoding (2025)"],
    image: "/images/iTrak/Screenshot%202026-08-14%20175457.png",
    link: "https://github.com/dayricraft",
    linkText: "View Project",
  },
  {
    num: "04",
    title: "Desa Gongseng Village Digital Portal",
    category: "Digital Web System",
    desc: "Digital village information portal developed during KKNT IPB University to modernize administrative record-keeping, improve public access, and support community digital services.",
    tech: ["Web Development", "Database Management", "MySQL", "UI/UX", "Data Organization"],
    awards: ["KKNT IPB University (2026)"],
    image: "/images/DocuTrack/login.png",
    link: "https://github.com/dayricraft",
    linkText: "View Project",
  },
];
